// acivitY 1 : diff between package-json and package-lock-json
//ANS : This is the main project file you write and edit
// It contains:
// Project info (name, version, author)
// Dependencies (with version ranges)
//  e.g. "express": "^4.18.0"
// Scripts (start, build, etc.)
//  Key idea:

// It defines what you want
// (not exact versions, but acceptable versions)



// Auto-generated by npm (you don’t manually edit it)
// Contains:
// Exact versions installed
// Full dependency tree (dependencies of dependencies)
// Integrity hashes (for security)
//  Key idea:

// It defines what was actually installed



//2: diff between dev dependencies and dependencies
// Used only during development
// Not needed in production
// Example: eslint, jest, prettier
// 👉 If removed → app still runs, but dev work harder
//vs
// dependencies
// Used when your app runs
// Required in production
// Example: express, axios
// 👉 If removed → app will break




// const express = require('express')
// const app = express()
// const port = 3000

// app.get('/', (req, res) => {
//   res.send('Welcome to HOME!')
// })
// app.get('/about', (req, res) => {
//   res.send('This is about page')
// })
// app.get('/contact', (req, res) => {
//   res.send('This is contact page')
// })
// //middleware use

// app.get('/project', (req, res) => {
//   res.send('This is project page')
// })
// app.listen(port, () => {
//   console.log(`Example app listening on port http://localhost:${port}`)
// })

const express = require('express')
const app = express()
const port = 3000

// function checkout(req,res,next) 
// {
//         console.log(req.url);
//         next();
// }

        app.use((req,res,next) => {
            console.log("middleware function",new Date());
        });

        app.get('/' ,(req,res) => 
        {
            res.send('Hello World!')
        });

        app.listen(port , () => 
        {
            console.log(`app listening on port http://localhost:${port}`);
        });
