CREATE DATABASE DEMO;

USE DEMO;

CREATE TABLE STUDENT (
    PRN INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    CGPA DECIMAL(10, 2) NOT NULL
);